config/routes.rb
Rails.application.routes.draw do
 
  resources :user_parents
  resources :designations
  resources :roles
  resources :permissions
  resources :module_groups
  get '/users/change_status'
  post '/users/reporting_manager'
   post '/downloads/mum_list_based_on_nd'
  get '/users/reset_password'
  post '/users/reset_password' => 'users#change_password' 

   post '/users/mum'
  post '/users/rds'
 
  resources :users 
  
  root "sessions#new"

  get  'forgot_password' =>'passwords#new',as: :passwords_new

  resources :passwords, only: [:create, :new, :update]
  resources :sessions, only: [:create,:destroy]
  get 'login' => 'sessions#new', as: :sign_in
  
    
  resources :users, only: [:create,:new] do
    resource :password, only: [:create, :edit, :update]
  end

  resources :permit_roles
  
  resources :sales_beats, only: [:index,:create,:new,:show]
  resources :targets
  resources :retailers, only: [:index,:create,:new,:show]
  resources :images
  resources :downloads
  post '/retailers/is_visited'

  namespace :api do
    namespace :v1 do
      resources :models, only: [:index]
      resources :sessions, only: [:create]
      resource :session, only: [:destroy]
      resources :passwords, only: [:create]
      resource :password,only: [:update]
      post  "/users/change_password", to: 'users#change_password' 
      get "/zsales/search", to: 'zsales#search'
      post "/zsales/assignment"
      post "/zsales/rds"
      post "/user", to: 'users#update'
      get "/versions", to: 'versions#index'
      post "/crash_reports", to: 'crash_reports#create'
    end
  end

  namespace :api do
    namespace :v2 do
      post "/zsales/rds" 
      post "/zsales/assignment"
    end
  end

end

app/models/module_group.rb
class ModuleGroup < ActiveRecord::Base
	has_many :permissions
end

app/controllers/module_groups_controller.rb
class ModuleGroupsController < ApplicationController
  before_action :set_module_group, only: [:show, :edit, :update, :destroy]

  # GET /module_groups
  # GET /module_groups.json
  def index
    @module_groups = ModuleGroup.all
  end

  # GET /module_groups/1
  # GET /module_groups/1.json
  def show
  end

  # GET /module_groups/new
  def new
    @module_group = ModuleGroup.new
  end

  # GET /module_groups/1/edit
  def edit
  end

  # POST /module_groups
  # POST /module_groups.json
  def create
    @module_group = ModuleGroup.new(module_group_params)

      if @module_group.save
        redirect_to module_groups_path
      else
       render :new 
      end
   
  end

  # PATCH/PUT /module_groups/1
  # PATCH/PUT /module_groups/1.json
  def update
    respond_to do |format|
      if @module_group.update(module_group_params)
        format.html { redirect_to module_groups_path, notice: 'Module group was successfully updated.' }
        format.json { render :show, status: :ok, location: @module_group }
      else
        format.html { render :edit }
        format.json { render json: @module_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /module_groups/1
  # DELETE /module_groups/1.json
  def destroy
    @module_group.destroy
    respond_to do |format|
      format.html { redirect_to module_groups_url, notice: 'Module group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_module_group
      @module_group = ModuleGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def module_group_params
      params.require(:module_group).permit(:name)
    end
end

app/helpers/module_groups_helper.rb
module ModuleGroupsHelper
end

app/views/module_groups/_form.html.erb
 

        <div id="content-wrapper">
          <div class="row">
            <div class="col-lg-12">
            <div class="main-box clearfix">
            <div class="clearfix">
              <div class="user_page">
               <h2>Add Module </h2>
             <%= form_for  @module_group do |f| %>
                  <div class="row">
                    <div class="col-md-10">
                      <div class="form-group clearfix">
                        <label class="col-md-2">Name</label>
                        <div class="col-md-7">
                            <%= f.text_field :name,:required => "required",class: "form-control",placeholder: "name" %>
                        </div>
                      </div>
                      
                    </div>
                    <!-- left part of form end --> 
                   
                     
                    <div class="col-md-3">
               <%= f.submit "Submit",:class => "btn btn-success rrm_frm_btn" %>
              
            </div>
            <div class="col-md-1">
               <%= link_to "Cancel",permissions_path,:class => "btn btn-danger ",data: { confirm: 'Are you sure?'} %>
              
            </div>
                  </div>
                 <% end %>
                </div>
              </div>
              </div>
            </div>
          </div>
          
          <footer id="footer-bar" class="row">
            <p id="footer-copyright" class="col-xs-12">
              Powered by Gionee
            </p>
          </footer>
        </div>
      </div>
    </div>
  </div>
    

 

app/views/module_groups/edit.html.erb
<h1>Editing Module Group</h1>

<%= render 'form' %>

<%= link_to 'Show', @module_group %> |
<%= link_to 'Back', module_groups_path %>

app/views/module_groups/index.html.erb
        
         <div id="content-wrapper">
            <div class="row">
          
          <div class="col-lg-12">
          <div class="add_new_notfcn">
            <h4><i class="fa fa-plus-square fa-lg"></i><span> <%= link_to "New Module", new_module_group_path %></span></h4>
          </div>
        </div>
          
            <div class="col-lg-12">
            <div class="main-box clearfix">
            <div class="clearfix">
              <div class="common_page gsb1">
              <div class="hdr">


                   <div class="row">
                <div class="col-md-2">
                  <h4>Module Group</h4>
                </div>
                 
              </div>    
            </div>
           
              
              <%@module_groups.each do |group_module|%>   
              <div id='content' class="tab-content">
                
                    <div class="tab-pane active" id="all">
                      <div class="row">
                      <div class="col-md-8">
                        <p><b>Group Name: </b><span class="blue"><%=group_module.name%></span></p>
                          
                        
                      </div>
                      
                      
                      <div class="col-md-1">
                      <ul class="list-inline list-unstyled">
                           
                        <li class="blue"><i class="fa fa-hand-o-right"></i><span><%= link_to 'Edit', edit_module_group_path(group_module) %></li>
                          
                        </ul>
                      </div>
                      <div class="col-md-1">
                      <ul class="list-inline list-unstyled">
                           
                        <li class="blue"><i class="fa fa-hand-o-right"></i><span><%=link_to :destroy,group_module, method: :delete, data: { confirm: 'Are you sure?' }%></span></li>
                          
                        </ul>
                      </div>
                    </div>
                   </div>
                   
                   

                   
                

</div>
               
              <%end%>
           
                 
                </div>
              </div>
              </div>
            </div>
          </div>
          
          <footer id="footer-bar" class="row">
            <p id="footer-copyright" class="col-xs-12">
              Powered by Gionee
            </p>
          </footer>
        </div>
      </div>
    </div>
  </div>
  

app/views/module_groups/new.html.erb
 

<%= render 'form' %>

app/views/module_groups/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_module_group_path(@module_group) %> |
<%= link_to 'Back', module_groups_path %>