config/routes.rb
Rails.application.routes.draw do
 
  resources :user_parents
  resources :designations
  resources :roles
  resources :permissions
  resources :module_groups
  get '/users/change_status'
  post '/users/reporting_manager'
   post '/downloads/mum_list_based_on_nd'
  get '/users/reset_password'
  post '/users/reset_password' => 'users#change_password' 

   post '/users/mum'
  post '/users/rds'
 
  resources :users 
  
  root "sessions#new"

  get  'forgot_password' =>'passwords#new',as: :passwords_new

  resources :passwords, only: [:create, :new, :update]
  resources :sessions, only: [:create,:destroy]
  get 'login' => 'sessions#new', as: :sign_in
  
    
  resources :users, only: [:create,:new] do
    resource :password, only: [:create, :edit, :update]
  end

  resources :permit_roles
  
  resources :sales_beats, only: [:index,:create,:new,:show]
  resources :targets
  resources :retailers, only: [:index,:create,:new,:show]
  resources :images
  resources :downloads
  post '/retailers/is_visited'

  namespace :api do
    namespace :v1 do
      resources :models, only: [:index]
      resources :sessions, only: [:create]
      resource :session, only: [:destroy]
      resources :passwords, only: [:create]
      resource :password,only: [:update]
      post  "/users/change_password", to: 'users#change_password' 
      get "/zsales/search", to: 'zsales#search'
      post "/zsales/assignment"
      post "/zsales/rds"
      post "/user", to: 'users#update'
      get "/versions", to: 'versions#index'
      post "/crash_reports", to: 'crash_reports#create'
    end
  end

  namespace :api do
    namespace :v2 do
      post "/zsales/rds" 
      post "/zsales/assignment"
    end
  end

end

app/models/designation.rb
class Designation < ActiveRecord::Base
	has_many :users
end

app/controllers/designations_controller.rb
class DesignationsController < ApplicationController
  before_action :set_designation, only: [:show, :edit, :update, :destroy]

  # GET /designations
  # GET /designations.json
  def index
    @designations = Designation.all
  end

  # GET /designations/1
  # GET /designations/1.json
  def show
  end

  # GET /designations/new
  def new
    @designation = Designation.new
  end

  # GET /designations/1/edit
  def edit
  end

  # POST /designations
  # POST /designations.json
  def create
    @designation = Designation.new(designation_params)

    respond_to do |format|
      if @designation.save
        format.html { redirect_to @designation, notice: 'Designation was successfully created.' }
        format.json { render :show, status: :created, location: @designation }
      else
        format.html { render :new }
        format.json { render json: @designation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /designations/1
  # PATCH/PUT /designations/1.json
  def update
    respond_to do |format|
      if @designation.update(designation_params)
        format.html { redirect_to @designation, notice: 'Designation was successfully updated.' }
        format.json { render :show, status: :ok, location: @designation }
      else
        format.html { render :edit }
        format.json { render json: @designation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /designations/1
  # DELETE /designations/1.json
  def destroy
    @designation.destroy
    respond_to do |format|
      format.html { redirect_to designations_url, notice: 'Designation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_designation
      @designation = Designation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def designation_params
      params.fetch(:designation, {})
    end
end

app/helpers/designations_helper.rb
module DesignationsHelper
end

app/views/designations/_form.html.erb
<%= form_for(@designation) do |f| %>
  <% if @designation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@designation.errors.count, "error") %> prohibited this designation from being saved:</h2>

      <ul>
      <% @designation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/designations/edit.html.erb
<h1>Editing Designation</h1>

<%= render 'form' %>

<%= link_to 'Show', @designation %> |
<%= link_to 'Back', designations_path %>

app/views/designations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Designations</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @designations.each do |designation| %>
      <tr>
        <td><%= link_to 'Show', designation %></td>
        <td><%= link_to 'Edit', edit_designation_path(designation) %></td>
        <td><%= link_to 'Destroy', designation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Designation', new_designation_path %>

app/views/designations/new.html.erb
<h1>New Designation</h1>

<%= render 'form' %>

<%= link_to 'Back', designations_path %>

app/views/designations/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_designation_path(@designation) %> |
<%= link_to 'Back', designations_path %>