config/routes.rb
Rails.application.routes.draw do
 
  resources :user_parents
  resources :designations
  resources :roles
  resources :permissions
  resources :module_groups
  get '/users/change_status'
  post '/users/reporting_manager'
   post '/downloads/mum_list_based_on_nd'
  get '/users/reset_password'
  post '/users/reset_password' => 'users#change_password' 

   post '/users/mum'
  post '/users/rds'
 
  resources :users 
  
  root "sessions#new"

  get  'forgot_password' =>'passwords#new',as: :passwords_new

  resources :passwords, only: [:create, :new, :update]
  resources :sessions, only: [:create,:destroy]
  get 'login' => 'sessions#new', as: :sign_in
  
    
  resources :users, only: [:create,:new] do
    resource :password, only: [:create, :edit, :update]
  end

  resources :permit_roles
  
  resources :sales_beats, only: [:index,:create,:new,:show]
  resources :targets
  resources :retailers, only: [:index,:create,:new,:show]
  resources :images
  resources :downloads
  post '/retailers/is_visited'

  namespace :api do
    namespace :v1 do
      resources :models, only: [:index]
      resources :sessions, only: [:create]
      resource :session, only: [:destroy]
      resources :passwords, only: [:create]
      resource :password,only: [:update]
      post  "/users/change_password", to: 'users#change_password' 
      get "/zsales/search", to: 'zsales#search'
      post "/zsales/assignment"
      post "/zsales/rds"
      post "/user", to: 'users#update'
      get "/versions", to: 'versions#index'
      post "/crash_reports", to: 'crash_reports#create'
    end
  end

  namespace :api do
    namespace :v2 do
      post "/zsales/rds" 
      post "/zsales/assignment"
    end
  end

end

app/models/user_parent.rb
class UserParent < ActiveRecord::Base
	belongs_to :parent,class_name: 'Role',foreign_key: 'parent_id'
	belongs_to :child,class_name: 'Role',foreign_key: 'child_id'
end

app/controllers/user_parents_controller.rb
class UserParentsController < ApplicationController
  before_action :set_user_parent, only: [:show, :edit, :update, :destroy]

  # GET /user_parents
  # GET /user_parents.json
  def index
    @user_parents = UserParent.all
  end

  # GET /user_parents/1
  # GET /user_parents/1.json
  def show
  end

  # GET /user_parents/new
  def new
    @user_parent = UserParent.new
  end

  # GET /user_parents/1/edit
  def edit
  end

  # POST /user_parents
  # POST /user_parents.json
  def create
    @user_parent = UserParent.new(user_parent_params)

    respond_to do |format|
      if @user_parent.save
        format.html { redirect_to user_parents_path, notice: 'User parent was successfully created.' }
        format.json { render :index, status: :created, location: @user_parent }
      else
        format.html { render :new }
        format.json { render json: @user_parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_parents/1
  # PATCH/PUT /user_parents/1.json
  def update
    respond_to do |format|
      if @user_parent.update(user_parent_params)
        format.html { redirect_to user_parents_path, notice: 'User parent was successfully updated.' }
        format.json { render :index, status: :ok, location: @user_parent }
      else
        format.html { render :edit }
        format.json { render json: @user_parent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_parents/1
  # DELETE /user_parents/1.json
  def destroy
    @user_parent.destroy
    respond_to do |format|
      format.html { redirect_to user_parents_url, notice: 'User parent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_parent
      @user_parent = UserParent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_parent_params
      params.require(:user_parent).permit(:parent_id,:child_id)
    end
end

app/helpers/user_parents_helper.rb
module UserParentsHelper
end

app/views/user_parents/_form.html.erb
<div id="content-wrapper">
   <%=  render :partial => "errors/error", :locals => { :errors => @user_parent.errors }%>
          <div class="row">
            <div class="col-lg-12">
            <div class="main-box clearfix">
            <div class="clearfix">
              <div class="user_page">
               <h2>Add Reporting Manager </h2>
             <%= form_for @user_parent do |f| %>
                  <div class="row">

                     <div class="col-md-6">
                      <div class="form-group clearfix">
                        <label class="col-md-3">Role</label>
                        <div class="col-md-9">
                          <%= f.select :child_id,Role.pluck(:name, :id),{:prompt => "--select child role--"},:class => 'form-control',:required => "required" %>
                        </div>
                      </div>
                      
                    </div>
                     
                    

                    <div class="col-md-6">
                      <div class="form-group clearfix">
                        <label class="col-md-3">Reporting Manager</label>
                        <div class="col-md-9">
                           <%= f.select :parent_id, Role.pluck(:name, :id),{:prompt => "--select parent role--"},:class => 'form-control',:required => "required" %>
                        </div>
                      </div>
                      
                    </div>
                    <!-- left part of form end --> 
                   
                    <div class="col-md-1">
               <%= f.submit "Submit",:class => "btn btn-success rrm_frm_btn" %>
              
            </div>
            <div class="col-md-2">
               <%= link_to "Cancel",user_parents_path,:class => "btn btn-danger ",data: { confirm: 'Are you sure?'} %>
              
            </div>
                  </div>
                 <% end %>
                </div>
              </div>
              </div>
            </div>
          </div>
          
          <footer id="footer-bar" class="row">
            <p id="footer-copyright" class="col-xs-12">
              Powered by Gionee
            </p>
          </footer>
        </div>
      </div>
    </div>
  </div>
    

app/views/user_parents/edit.html.erb
 
<%= render 'form' %>
 

app/views/user_parents/index.html.erb
<div id="content-wrapper">
               
  <div class="row">
     <div class="col-lg-12">
        <div class="main-box-body clearfix">
            <div class="row">
            
            <div class="col-md-3">
                <div class="add_new_notfcn">
                  <h4><i class="fa fa-plus-square fa-lg"></i>
                    <span>
          <%= link_to "Add Reporting Manager", new_user_parent_path %>
             </span>
                  </h4>
                </div>
              </div>
             
            </div>
            </div>
          </div>
        </div>

  <div class="row">
    <div class="col-lg-12">
        <div class="main-box clearfix">
          <div class="clearfix">
              <div class="common_page user">
              <div class="user_tab">
              <div class="row">
                <div class="col-md-2">
                  <h4>Reporting Manager</h4>
                </div>
              
               
              </div>
              </div>

                <div id='content' class="tab-content" >
               <% @user_parents.each do |user_parent| %>
              
                    <div class="tab-pane active" id="all">
                      <div class="row">
                          <div class="col-md-9">

                            <p> <span class="blue">  <%= user_parent.parent.name %> </span>
                             
                              <span class="role_of_user"> 
                                 
                              <%= user_parent.child.name %>
                                                        
                       </span> 

                       </p>
                             
                          </div>

                          <div class="col-md-3">
                              <ul class="list-inline list-unstyled">
                              
                                <li class="blue">
                                  <i class="fa fa-pencil"></i>
                                  
                                  
                                  <span>
                                    <%= link_to "Edit", [:edit, user_parent] %>
                                  </span>
                                  

                                </li>
                              
                                 

                              </ul>
                          </div>
                        </div>
                    </div>

              <% end %>
              
                </div>

                </div>
              </div>
              </div>
            </div>
          </div>
   
        </div>

   

app/views/user_parents/new.html.erb
 
<%= render 'form' %>

 